version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: fix
      include: scope
    ignore:
      - dependency-name: "node"
        versions: ["16.x"]
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: fix
      include: scope
    ignore:
      - dependency-name: "@types/node"
        versions: ["16.x"]
